#!/usr/bin/perl

###############################################################################
# Greymatter 1.8.2                            
# Copyright (c)2000-2008, The Greymatter team 
# http://greymatterforum.proboards82.com/     
# By possessing this software, you agree not to hold the author responsible for 
# any problems that may arise from your installation or usage of Greymatter 
# itself, or from any content generated by yourself or others through the use of 
# this program.  You MAY freely modify and redistribute this program, so 
# long as every copyright notice (including in this manual and in the Greymatter 
# code) remains fully intact.  Finally, you may NOT sell or in any way 
# make a financial profit from this program, either in original or modified form.
# Your possession of this software signifies that you agree to these terms; 
# please delete your copy of this software if you don't agree to these terms.
# Original Creator Noah Grey
###############################################################################

# TODO INTEGRATE BACK INTO
# GM.CGI AS THIS IS ADMIN FUCNTIONALITY AND SHOULD REMAIN GROUPED

########### THIS FILE HAS BEEN DEPRECATED BY: uploadFile in gm.cgi ####################

	die( "gm_upload.cgi has been DEPRECATED");
